version: '3.5'
services:
  postgres:
    container_name: test_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - database
    restart: unless-stopped

networks:
  database:
    driver: bridge

volumes:
  db: